version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: '.'
    volumes:
      - ./src:/var/www/html
  db:
    ports:
      - "3306:3306"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db 